name: Build Release ZIP

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-zip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get version from git tag
      id: vars
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

    - name: Create ZIP archive with version in name
      run: |
        zip -r pf2e-galactic-hero-points-variant-${VERSION}.zip pf2e-galactic-hero-points-variant/
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: pf2e-galactic-hero-points-variant-${{ env.VERSION }}.zip
        path: pf2e-galactic-hero-points-variant-${{ env.VERSION }}.zip
